eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="$PATH:~/.local/bin/"

alias v="nvim"
alias ll="ls -al"
alias gstat="git status"
alias gcom="git commit -m"
alias gcam="git commit -am"
alias newb="git checkout -b"
alias check="git checkout"
alias gbr="git branch"
alias gpull="git pull"
alias gpush="git push"
alias togenemod="cd ~/projects/genemod"
alias tobe="cd ~/projects/genemod/backend/src"
alias tofe="cd ~/projects/genemod/app"
alias toyjs="cd ~/projects/genemod/yjs"
