eval "$(/opt/homebrew/bin/brew shellenv)"

alias v="nvim"
alias ll="ls -al"
alias gstat="git status"
alias gcom="git commit -m"
alias gcam="git commit -am"
alias newb="git checkout -b"
alias check="git checkout"
alias gbr="git branch"
alias gpull="git pull"
alias gpush="git push"
alias togenemod="cd ~/Documents/genemod"
alias tobe="cd ~/Documents/genemod/backend/src"
alias tofe="cd ~/Documents/genemod/app"
